services:
  web:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    command: bundle exec foreman start -f ${PROCFILE:-./Procfile.dev}
    # command: tail -f /dev/null
    volumes:
      - .:/rails
      - ../res:/res
    depends_on:
      - db
    environment:
      EDITOR: vi
    user: "${DOCKER_EXEC_USER:-root}"
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - .:/app
      - ../res:/res
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    restart: always
    user: root

volumes:
  postgres:
